import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,raw_user_meta_data jsonb,email text); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; GRANT USAGE ON SCHEMA public,auth TO authenticated; GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated; CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text primary key,name text,public boolean); CREATE TABLE storage.objects(id uuid,bucket_id text,name text); CREATE FUNCTION storage.foldername(text) RETURNS text[] LANGUAGE sql AS $$SELECT string_to_array($1,'/')$$;`);
for(const name of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO authenticated');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',w='33333333-3333-4333-8333-333333333333',e='44444444-4444-4444-8444-444444444444';
await db.query('INSERT INTO auth.users(id,email) VALUES($1,$2),($3,$4)',[a,'a@test.invalid',b,'b@test.invalid']);
await db.query(`INSERT INTO workouts(id,user_id,nome) VALUES($1,$2,'Treino A')`,[w,a]);
await db.query(`INSERT INTO exercises(id,user_id,nome,tipo_controle,musculo_principal,categoria) VALUES($1,$2,'Supino','peso_kg','chest','musculacao')`,[e,a]);
const payload={id:'55555555-5555-4555-8555-555555555555',workout_id:w,nome_treino:'Treino A',iniciado_em:new Date().toISOString(),finalizado_em:new Date().toISOString(),volume_total:100,sets:[{id:'66666666-6666-4666-8666-666666666666',exercise_id:e,nome_exercicio:'Supino',musculo_principal:'chest',musculos_secundarios:['triceps'],serie_numero:1,repeticoes:10,carga_kg:10,concluida:true,kind:'normal'}]};
await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${a}'`);
await db.query('SELECT save_workout_snapshot($1)',[payload]);await db.query('SELECT save_workout_snapshot($1)',[payload]);
assert.equal((await db.query('SELECT * FROM workout_sessions')).rows.length,1);assert.equal((await db.query('SELECT * FROM set_logs')).rows.length,1);
await db.exec(`SET request.jwt.claim.sub='${b}'`);assert.equal((await db.query('SELECT * FROM workout_sessions')).rows.length,0);await assert.rejects(db.query('SELECT save_workout_snapshot($1)',[payload]));
await db.exec(`SET request.jwt.claim.sub='${a}'`);await assert.rejects(db.query('SELECT save_workout_snapshot($1)',[{...payload,sets:[{...payload.sets[0],exercise_id:'77777777-7777-4777-8777-777777777777'}]}]));assert.equal((await db.query('SELECT * FROM set_logs')).rows.length,1);
console.log('PASS: two-user isolation, duplicate retries, rollback on invalid exercise.');await db.close();
