import { Brand } from "@/components/Brand";
import { Trophy } from "lucide-react";
import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { useAuth } from '@/hooks/use-auth';
import { supabase } from '@/integrations/supabase/client';
import { readDraft, saveDraft, remaining, totals, type Draft, type Exercise } from '@/lib/workout-storage';
import { syncDraft } from '@/lib/workout-sync';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LiveMuscleMap } from '@/components/LiveMuscleMap';
import type { BodyGender } from '@/components/MuscleBody';
export const Route = createFileRoute('/_authenticated/run/$workoutId')({component: Run});
function Run(){
 const {user}=useAuth(); const {workoutId}=Route.useParams();
 const [historyRows,setHistoryRows]=useState<{exercise_id:string|null;carga_kg:number|null;repeticoes:number|null}[]>([]);
 const [choices,setChoices]=useState<{id:string;nome:string;musculo_principal:string;musculos_secundarios:string[];musculos_terciarios?:string[]}[]>([]);
 useEffect(()=>{if(user)supabase.from('exercises').select('id,nome,musculo_principal,musculos_secundarios,musculos_terciarios').order('nome').then(({data})=>setChoices(data||[]))},[user?.id]);
 const [sound,setSound]=useState(false);
 const [bodyGender,setBodyGender]=useState<BodyGender>('male');
 useEffect(()=>{if(!user)return;Promise.resolve(supabase.from('profiles').select('sex').eq('id',user.id).maybeSingle()).then(({data})=>setBodyGender(data?.sex==='feminino'?'female':'male')).catch(()=>{});},[user?.id]);
 const [draft,setDraft]=useState<Draft|null>(null); const [now,setNow]=useState(Date.now()); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!user)return; let active=true;
 (async()=>{ const old=readDraft(user.id); if(old && (!old.finished || !old.synced)){if(active)setDraft(old);return;}
 const [{data:w,error:we},{data:rows,error:re},{data:history}]=await Promise.all([
 supabase.from('workouts').select('nome').eq('id',workoutId).eq('user_id',user.id).single(),
 supabase.from('workout_exercises').select('*,exercises(nome,musculo_principal,musculos_secundarios,musculos_terciarios)').eq('workout_id',workoutId).eq('user_id',user.id).order('ordem'),
 supabase.from('set_logs').select('exercise_id,carga_kg,repeticoes').eq('user_id',user.id).eq('concluida',true).order('created_at',{ascending:false}).limit(500)]);
 if(we||re)throw we||re;
 if(active)setHistoryRows(history||[]);
 const d:Draft={id:crypto.randomUUID(),userId:user.id,workoutId,name:w!.nome,started:Date.now(),restUntil:0,exercises:(rows||[]).map(r=>{const prev=history?.find(h=>h.exercise_id===r.exercise_id);return {exercise_id:r.exercise_id,nome:r.exercises?.nome||'Exercício',musculo_principal:r.exercises?.musculo_principal||'',musculos_secundarios:r.exercises?.musculos_secundarios||[],musculos_terciarios:r.exercises?.musculos_terciarios||[],descanso_seg:r.descanso_seg,previous:prev?`${prev.repeticoes} × ${prev.carga_kg} kg`:undefined,sets:Array.from({length:r.series},()=>({id:crypto.randomUUID(),reps:String(prev?.repeticoes??r.repeticoes),carga:String(prev?.carga_kg??r.carga_kg??0),done:false,kind:'normal'}))}})};
 saveDraft(d); if(active)setDraft(d);
 })().catch(e=>setError(e.message||'Não foi possível abrir o treino.'));return()=>{active=false};},[user?.id,workoutId]);
 useEffect(()=>{if(!user)return;const t=setInterval(()=>{const d=readDraft(user.id);if(d&&!d.synced)syncDraft(d).then(ok=>{if(ok)setStatus('Salvo na sua conta')}).catch(()=>{});},10000);return()=>clearInterval(t)},[user?.id]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!draft)return; const t=setTimeout(()=>{syncDraft(draft).then(ok=>setStatus(ok?'Salvo na sua conta':'Salvo no aparelho • sincronização pendente')).catch(()=>setStatus('Salvo no aparelho • sincronização pendente'));},700);return()=>clearTimeout(t)},[draft]);
 useEffect(()=>{const online=()=>{if(draft)syncDraft(draft).then(ok=>setStatus(ok?'Sincronizado':'Pendente')).catch(()=>setStatus('Sincronização pendente'))};window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[draft]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(draft&&!draft.finished){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[draft]);
 useEffect(()=>{if(draft?.restUntil && remaining(draft.restUntil,now)===0){navigator.vibrate?.([200,100,200]);if(sound){try{const a=new AudioContext();const o=a.createOscillator();o.connect(a.destination);o.start();o.stop(a.currentTime+0.25);o.onended=()=>a.close();}catch{}}update({...draft,restUntil:0});}},[now]);
 function update(d:Draft){try{saveDraft(d);setDraft(d)}catch{toast.error('Armazenamento cheio. Não foi possível salvar a alteração.')}}
 function change(ei:number,fn:(e:Exercise)=>Exercise){if(draft)update({...draft,exercises:draft.exercises.map((e,i)=>i===ei?fn(e):e)})}
 if(error)return <main className="p-6"><p role="alert">{error}</p><Link to="/workouts">Voltar aos treinos</Link></main>;
 if(!draft)return <main className="p-6" aria-busy="true">Preparando seu treino…</main>;
 const stats=totals(draft); const rest=remaining(draft.restUntil,now);
 if(draft.finished)return <main className="eforge-finished mx-auto max-w-md p-5"><Brand /><div className="eforge-finish-trophy"><Trophy size={64} strokeWidth={1.5}/></div><h1 className="text-3xl">Treino concluído</h1><p className="my-6">{stats.sets} séries • {stats.volume.toLocaleString('pt-BR')} kg</p><p role="status">{status}</p><Link className="block py-4 text-neon" to="/muscle-map">Ver músculos trabalhados</Link><Link to="/workouts">Meus treinos</Link></main>;
 return <main className="eforge-run mx-auto max-w-lg px-4 pb-32"><div className="flex justify-between"><Link to="/workouts" onClick={e=>{if(!confirm('Sair da tela? Seu treino ficará salvo para continuar.'))e.preventDefault()}}>← Salvar e sair</Link><Brand compact /></div><h1 className="text-3xl mt-5">{draft.name}</h1><label className="block py-3"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Som no fim do descanso</label><p className="text-sm text-muted-foreground my-3" role="status">{status}</p><div className="flex justify-between surface p-4 rounded-2xl"><strong>{Math.floor((now-draft.started)/60000)} min</strong><span>{stats.sets} séries</span><strong>{stats.volume.toLocaleString('pt-BR')} kg</strong></div>
 <LiveMuscleMap draft={draft} gender={bodyGender} />
 {rest>0&&<div className="eforge-rest sticky top-2 z-30 rounded-2xl p-3 my-4 flex items-center justify-between"><button onClick={()=>update({...draft,restUntil:Math.max(Date.now(),draft.restUntil-15000)})}>−15s</button><strong role="timer">Descanso {rest}s</strong><button onClick={()=>update({...draft,restUntil:draft.restUntil+15000})}>+15s</button><button onClick={()=>update({...draft,restUntil:0})}>Pular</button></div>}
 {draft.exercises.map((e,ei)=><section className="surface rounded-2xl p-4 mt-4" key={e.exercise_id}><h2 className="text-xl">{e.nome}</h2><select className="w-full my-2 p-2" aria-label="Substituir exercício" value="" onChange={ev=>{const c=choices.find(c=>c.id===ev.target.value);if(!c)return;if(e.sets.some(s=>s.done)&&!confirm('Substituir remove as séries deste exercício. Continuar?'))return;change(ei,x=>({...x,exercise_id:c.id,nome:c.nome,musculo_principal:c.musculo_principal,musculos_secundarios:c.musculos_secundarios,musculos_terciarios:c.musculos_terciarios??[],previous:undefined,sets:x.sets.map(s=>({...s,id:crypto.randomUUID(),done:false,carga:'0'}))}))}}><option value="">Substituir exercício…</option>{choices.filter(c=>!draft.exercises.some(x=>x.exercise_id===c.id)).map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select><p className="text-sm text-muted-foreground my-2">Anterior: {e.previous||'Primeiro registro'}</p><details><summary className="py-3 text-neon">Séries anteriores</summary>{historyRows.filter(h=>h.exercise_id===e.exercise_id).slice(0,12).map((h,i)=><p className="text-sm py-1" key={i}>{h.repeticoes} repetições × {h.carga_kg} kg</p>)}</details><div className="grid grid-cols-[30px_1fr_1fr_44px] gap-2 text-xs text-muted-foreground"><span>Série</span><span>Repetições</span><span>Carga kg</span><span>Feita</span></div>{e.sets.map((s,si)=><div key={s.id} className="mt-3"><div className="grid grid-cols-[30px_1fr_1fr_44px] gap-2 items-center"><span>{si+1}</span>{(['reps','carga'] as const).map(k=><Input key={k} aria-label={`${e.nome} série ${si+1} ${k==='reps'?'repetições':'carga'}`} inputMode={k==='reps'?'numeric':'decimal'} value={s[k]} onChange={ev=>{const value=ev.target.value;if((k==='reps'?/^\d*$/:/^\d*([.,]\d*)?$/).test(value))change(ei,x=>({...x,sets:x.sets.map(a=>a.id===s.id?{...a,[k]:value}:a)}))}} className="h-12"/>)}<button aria-label="Concluir série" aria-pressed={s.done} className={`rounded-xl h-12 ${s.done?'bg-neon':'surface-2'}`} onClick={()=>{const ex=draft.exercises.map((x,i)=>i!==ei?x:{...x,sets:x.sets.map(a=>a.id===s.id?{...a,done:!a.done}:a)});update({...draft,exercises:ex,restUntil:!s.done?Date.now()+e.descanso_seg*1000:draft.restUntil});navigator.vibrate?.(40);}}>✓</button></div><div className="flex justify-between mt-1"><select aria-label="Tipo da série" value={s.kind} onChange={ev=>change(ei,x=>({...x,sets:x.sets.map(a=>a.id===s.id?{...a,kind:ev.target.value}:a)}))}><option value="normal">Normal</option><option value="warmup">Aquecimento</option><option value="drop">Drop-set</option><option value="failure">Falha</option></select><button aria-label="Remover série" onClick={()=>change(ei,x=>({...x,sets:x.sets.filter(a=>a.id!==s.id)}))}>Remover</button></div></div>)}<button className="w-full text-neon mt-2" onClick={()=>change(ei,x=>({...x,sets:[...x.sets,{...(x.sets.at(-1)||{reps:'10',carga:'0',kind:'normal'}),id:crypto.randomUUID(),done:false}]}))}>+ Adicionar série</button></section>)}
 <div className="fixed bottom-0 inset-x-0 p-4 bg-background border-t border-border" style={{paddingBottom:'max(1rem,env(safe-area-inset-bottom))'}}><Button disabled={saving} className="w-full max-w-lg mx-auto block h-12" onClick={async()=>{if(!stats.sets)return toast.error('Conclua ao menos uma série.');if(!confirm('Finalizar o treino com as séries concluídas?'))return;setSaving(true);const d={...draft,finished:Date.now(),restUntil:0};update(d);try{await syncDraft(d)}catch{toast('Treino salvo no aparelho. Será sincronizado ao reconectar.')}finally{setSaving(false)}}}>Finalizar treino</Button></div></main>
}
